#!/bin/sh

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
set -eu

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

#
NOTICE "[NODEJS] -- Starting Service nodejs ..."

# Redirect STDERR to STDOUT
exec 2>&1

# Let's go and start node
exec su-exec node node

# This exit code will be sent as the first parameter to the finish script
exit 1

